### PR TITLE
Fix for macOS executable and 2 additional Unix executables

### PR DESCRIPTION
**Pull request by remlapmot**
Firstly, thanks indeed for this fantastic package and also for you SASmarkdown package. It is brilliant to be able to use Stata in Rmd files.

## Two small fixes for your consideration:

1. I think your macOS executable code needed this small fix. Essentially I don't think that your old code worked, hence I just deleted that part. Your *new* code is correct. 

    (Apologies if you know all this) On macOS the `.app` file for an app is really a folder with the executables and other stuff inside. On macOS in for Stata in its .app/Contents/MacOS folder it actually has 2 executables, one for the GUI, which you're hitting and another for the executable for the Terminal (i.e. there's `stata` and `Stata`; or `stata-se` and `StataSE`, or `stata-mp` and `StataMP` depending upon which version you have). I think it's better to hit the `Stata` executable as you're doing as that one draws the plots in memory so you can `graph export` them in the Stata code chunk and then show them in a subsequent code chunk in your Rmd file.

2. As far as I remember the executables for the different versions of Stata on Unix have 3 different names (`stata`, `stata-se`, `stata-mp`). You were just looking for `stata`, so I added searching over all 3.

## Possible outstanding error
I think both the Mac and Unix versions may fail to run the Stata code chunks if the .Rmd file is saved in a filepath which has a space in its name. This is because Terminal commands of the form
```
stata -q -e do "/filepath with spaces/mydofile"
```
seem to fail (or at least they do on my Stata 15) even if I put quotes around the filepath. I suspect this may be a bug in the way Stata parses the command so I might ask Tech Support about this. 

## .Rproj file
Also personally I prefer to include my .Rproj files in my repos (i.e. remove this from your `.gitignore` but I agree `.Rproj.user` should be ignored). Note that you can add `.Rproj` and `.Rproj.user` to a `.Rbuildignore` file so those files don't get included in the built package.

Best wishes
  Tom Palmer

### CODE REVIEW

**Comment by Hemken** [comment]
Thanks.  Saw this email as I was heading out the door for a vacation – I’ll look into these when I return.

**Comment by Hemken** [comment]
Probably want to flip the search order, to use the most powerful Stata?  On our linstat I find: stata-mp, stata-se, stata-ic, and a link, “stata” pointing to stata-mp.

**Comment by remlapmot** [comment]
That's interesting. 

On my Mac (I only have Stata SE version 15.1 on a Mac to test with) in Stata "Install Terminal Utility" puts a symbolic link, `stata-se`, in `/usr/local/bin/` (which points at the binary within the app folder `/Applications/Stata/StataSE.app/Contents/MacOS/stata-se`). 

Maybe the `stata` link always exists on Unix installations (but not on Mac)? Anyway, I'm happy to make the change about the order (if the `stata` link always exists clearly the other names won't matter). Or maybe the `stata` link is new for version 16.

**Comment by remlapmot** [comment]
I have

- Changed the order of the executable lnk names
- Unignored the `.Rproj` file, as it was easier for me to debug the last commits using RStudio project mode
- The last 2 commits allow for a filepath to have a space in because the bug (which Tech Support have confirmed to me) which Stata has in parsing do-file names on macOS and Unix is predictable, i.e.
    ```
    stata-se -q -e do \"/Users/username/my docs/test.do\"
    ```
    produces `my.log` instead of `test.log`, i.e. it's taking the name of the log-file from upto the first space.

I have tested these on macOS but not on Linux.

cheers
  Tom

**Comment by Hemken** [comment]
Thanks for all this!  I should be back on line and able to review in 2 weeks.

**Pull request closed without merging**
